### ISSUE TITLE
JavaScript framework?

### ISSUE THREAD

**Issue by ghost** [ReDetection/vkradio#3]
What about to use one of the JavaScript frameworks from [this](http://todomvc.com/) list?

**Comment by ReDetection** [comment]
Maybe. I'm not an experienced JS developer so I have no idea what is the best for me. You saw my code, you saw my TODOs, so can you offer something? But when you do, please tell me the reason why should I use it. How can it help me? (because I have absolutely no idea why do I need it)
For now my code is simple enough to work on many browsers including modern mobile devices, so that framework should not narrow compatibility list.

**Comment by ghost** [comment]
> I'm not an experienced JS developer so I have no idea what is the best for me.

Just like me.

I will try to use [Backbone.js](http://backbonejs.org/) in my fork. I hope to get all this things from their main page:

> Backbone.js gives structure to web applications by providing models with key-value binding and custom events, collections with a rich API of enumerable functions, views with declarative event handling, and connects it all to your existing API over a RESTful JSON interface.

**Comment by ReDetection** [comment]
Thanks for bootstrap, I've merged with your branch a little :)
P.S. Note that vk api calls is allowed for 127.0.0.1 so everything will work from your local web server.
